CREATE TABLE user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,

    username VARCHAR(200) NOT NULL ,
    password_hash VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL ,
    name VARCHAR(50) NOT NULL,
    birth DATETIME NOT NULL,
    phone_number VARCHAR(13) NOT NULL ,
    address VARCHAR(200) NOT NULL,
    role VARCHAR(8) NOT NULL ,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
)