CREATE TABLE purchase_product(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,

    purchase_id BIGINT NOT NULL ,
    product_id BIGINT NOT NULL ,

    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP
)