spring:
  application:
    name: commerce

  # ?????? ?? ??
  datasource:
    # jdbc?? ????? ??, localhost:3306?? mysql? ????? ??????? spring_db
    url: jdbc:mysql://localhost:3306/commerce?useSSL=false&allowPublicKeyRetrieval=true
    username: root  # ??? ?? ????? ? (?, ????? ???? ???? root ???? ? ?)
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ? Hibernate ??
  jpa:
    hibernate: # jpa? ????? ?? ?! (??? ??? ??)
      # ddl-auto: ?????? ?? ? ???(???) ?? ??
      # none: ?? ??? ?? ?? (?? ?? ??)  # ????? none ?? ?! create ?? X
      # create: ?? ??? ?? ? ?? ??
      # update: ??? ??? ??
      ddl-auto: none
    properties:
      hibernate: # hibernate? ?? ?? MySQL? ?? ?
        # MySQL 8 ??? ?? Dialect(??) ??
        dialect: org.hibernate.dialect.MySQL8Dialect  # ORM?? ???? ???? SQL? ?? DB? ?? ??? SQL?? ??? ?? ??? ??

  # ?? ?? ??
  logging:
    level:
      # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
      org.hibernate.SQL: DEBUG

  flyway:
    enabled: false # Flyway ???
    # ?????? ?? ?? ?? (???) classpath? resource ???? ???! ? ?? resource ??? ??? db ????? migration ????
    locations: classpath:db/migration
    baseline-on-migrate: true # ??? ???? ?? DB? Flyway? ?? ??? ?? ??? true!!

  hikari:
    maximum-pool-size: 10  # ?? ??? ??
    connection-timeout: 30000 # ???? ?? ?? ???? ?? ?? (ms)
    max-lifetime: 1800000 # ???? ?? ?? (ms)

# ?? ? ?? ??
server:
  port: 8080

# Swagger UI ?? (Springdoc)
springdoc:
  swagger-ui:
    enabled: true