spring:
  profiles:
    active: secret
  config:
    import: optional:file:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    enabled: true # 서버에 올릴 때는 false

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  port: 8080