spring:
  profiles:
    active: secret
  config:
    import: optional:file:application-secret.yml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      max-lifetime: 1800000

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  port: 8080