spring:
  application:
    name: java-02
  datasource:
    url: jdbc:mysql://localhost:3406/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  # ✅ flyway는 spring 블록 "밖에" 있어야 함!
logging:
  level:
    org.hibernate.SQL: DEBUG
springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080
