spring:
  application:
    name: ecommerce
  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://localhost:13306/project_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      max-lifetime: 1800000

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true


  flyway:
    enabled: true # Flyway 활성화
    # 마이그레이션 파일 위치 지정 (기본값)
    locations: classpath:db/migration
    baseline-on-migrate: true # 기존에 테이블이 있는 DB에 Flyway를 처음 적용할 때 사용

# 내장 웹 서버 설정
server:
  port: 8080

# Swagger UI 설정 (Springdoc)
springdoc:
  swagger-ui:
    enabled: true # 라이브 시에는 false로 변경하여 스웨거를 끈다.

# 로깅 레벨 설정
logging:
  level:
    # Hibernate가 실행하는 SQL 쿼리를 DEBUG 레벨로 로그에 출력
    org.hibernate.SQL: DEBUG