spring:
  application:
    name: project-week1

  datasource:
    hikari:
    #      maximum-pool-size: 10 # 최대 커넥션 수
    #      connection-timeout: 30000 # 커넥션을 얻기 위해 대기하는 최대 시간 (ms)
    #      max-lifetime: 1800000 # 커넥션의 최대 수명
    url: jdbc:mysql://localhost:3307/spring_education_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      # ddl-auto: 애플리케이션 실행 시 스키마(테이블) 처리 전략
      # none: 아무 작업도 하지 않음 (운영 환경 추천)
      # create: 기존 테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      ddl-auto: none
    properties:
      hibernate:
        # MySQL 8 버전에 맞는 Dialect(방언) 설정
        dialect: org.hibernate.dialect.MySQL8Dialect

        # sql 로깅을 위해 추가
        format_sql: true
        highlight_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger UI 설정
springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080