spring:
  application:
    name: sparta-java-2-project-part-1

  datasource:
    url: jdbc:mysql://localhost:3306/project_1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: DEBUG

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true