CREATE TABLE product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT '상품명',
    description VARCHAR(255) COMMENT '상품 설명',
    price DECIMAL(10, 6) NOT NULL COMMENT '상품 가격',
    stock INT NOT NULL DEFAULT 0 COMMENT '재고 수량',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
