CREATE TABLE `user` (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nick_name VARCHAR(20) UNIQUE NOT NULL,
  phone VARCHAR(20) UNIQUE,
  address TEXT NOT NULL,
  age INTEGER NOT NULL,
  gender CHAR(1) NOT NULL COMMENT 'M: 남성, F: 여성',
  refund_account_holder VARCHAR(100) NOT NULL COMMENT '환불 계좌 예금주 이름',
  refund_bank_name VARCHAR(100) NOT NULL COMMENT '환불 계좌 은행명',
  refund_account_number VARCHAR(50) NOT NULL COMMENT '환불 계좌번호',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE product(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  brand_name VARCHAR(50),
  price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  category_id BIGINT COMMENT '상품이 속한 카테고리 ID',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE category (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  parent_id BIGINT DEFAULT NULL COMMENT '부모 카테고리 ID (자기 참조)',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE purchase (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL COMMENT '구매한 사용자 ID',
  total_price DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING, COMPLETED, CANCELED',
  shipping_address TEXT NOT NULL,
  recipient_name VARCHAR(100) NOT NULL COMMENT '수령인 이름',
  recipient_phone VARCHAR(20) NOT NULL COMMENT '수령인 연락처',
  created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE purchase_product (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  purchase_id BIGINT NOT NULL COMMENT '어떤 주문에 속하는지',
  product_id BIGINT NOT NULL COMMENT '어떤 상품인지',
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL COMMENT '주문 시점의 상품 가격',
  created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE cart (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INT NOT NULL,
  brand_name VARCHAR(100),
  total_price DECIMAL(10,2) NOT NULL
);

CREATE TABLE refund (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  purchase_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'REQUESTED' COMMENT 'REQUESTED, APPROVED, COMPLETED, REJECTED',
  refund_amount DECIMAL(10,2) NOT NULL COMMENT '환불 금액',
  reject_reason TEXT
);