spring:
  application:
    name: project

  datasource:
    url: jdbc:mysql://localhost:3307/spring_project_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

  flyway:
    enabled:true
    locations:classpath:db/migration

  springdoc:
    swagger-ui:
      enabled: true

server:
  port: 8090