ALTER TABLE user
    ADD COLUMN address VARCHAR(255) NOT NULL;
ALTER TABLE user
    ADD COLUMN address_detail VARCHAR(255);
ALTER TABLE user
    ADD COLUMN zipcode VARCHAR(10) NOT NULL;
ALTER TABLE user
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user
    ADD COLUMN deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP;