CREATE TABLE purchase (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '구매 ID',
    user_id         BIGINT NOT NULL COMMENT '구매한 사용자 ID FK',
    total_price     DECIMAL(10, 2) NOT NULL COMMENT '전체 결제 가격',
    status          VARCHAR(30) DEFAULT 'CREATED'
        COMMENT '구매상태 : CREATED, PAYMENT_PENDING, PAID, PAYMENT_FAILED, ORDER_CONFIRMED
        ,PREPARING_SHIPMENT, SHIPPED, DELIVERED, COMPLETED, CANCELLED, RETURNED, EXCHANGED',
    payment_method  VARCHAR(30) DEFAULT NULL COMMENT '결제 수단: CARD, BANK, MOBILE, PAY, VIRTUAL',
    paid_at         DATETIME DEFAULT NULL COMMENT '결제 완료 시각',
    shipping_addr   TEXT NOT NULL COMMENT '배송 주소',
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
    updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);