CREATE TABLE purchase (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_price DECIMAL(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    tracking_number VARCHAR(255),
    payment_type VARCHAR(20) NOT NULL,
    address VARCHAR(255),

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);