CREATE TABLE refund (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    purchase_id BIGINT NOT NULL COMMENT '환불할 주문 ID',
    user_id BIGINT NOT NULL COMMENT '환불할 신청 사용자 ID',
    refund_price DECIMAL(10, 2) NOT NULL COMMENT '환불 금액',
    reason TEXT COMMENT '환불 사유',
    status VARCHAR(20) NOT NULL DEFAULT 'REQUESTED' COMMENT 'REQUESTED, PROCESSING, COMPLETED, REJECTED',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
